const data = {
  products: [
    {
      name: 'DN16343',
      slug: 'DN-16343-gold',
      category: 'Fell Kids',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Feel Kids',
      rating: 4.5,
      numReviews: 10,
      description: 'Pure cotton',
    },
    {
      name: 'DN17144',
      slug: 'DN-17144-pink',
      category: 'Feel Kids',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Feel Kids',
      rating: 4.6,
      numReviews: 10,
      description: 'Pure cotton',
    },
    {
      name: 'DN17235',
      slug: 'DN-17235-pink',
      category: 'Feel Kids',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'Feel Kids',
      rating: 4.5,
      numReviews: 10,
      description: 'Pure cotton',
    },
    {
      name: 'DN17180',
      slug: 'DN-17180-green',
      category: 'Feel Kids',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 25,
      brand: 'Feel Kids',
      rating: 4.8,
      numReviews: 10,
      description: 'Pure cotton',
    },
  ],
};

export default data;
